[build]
  base ="/"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200
  force = true